# Generated by Django 4.2.18 on 2025-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('plot_summary', models.TextField()),
            ],
        ),
    ]
