# Generated by Django 4.2.18 on 2025-01-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_keyword_movie_genres_movie_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
